...@classes
# ...@connections

ext: external network {
  class: ext
  nested container: {
    class: ext_c
    2nd nested container: {
      class: ext_cc
    }
  }
}
dc: datacenter {
  class: dc
  nested container: {
    class: dc_c
    2nd nested container: {
      class: dc_cc
    }
  }
}
campus: campus {
  class: campus
  nested container: {
    class: campus_c
    2nd nested container: {
      class: campus_cc
    }
  }
}
