classes: {
  ext: {
    label.near: bottom-left
    near: top-left
    style: {
      opacity: 0.4
      fill: "#FDF2D0"
      stroke: "#FDF2D0"
      font-size: 30
    }
  }
  ext_c: {
    style: {
      opacity: 0.9
      fill: "#FDF2D0"
      stroke: "#b18708"
      font-size: 30
    }
  }
  ext_cc: {
    style: {
      opacity: 0.9
      fill: "#fae08e"
      stroke: "#b18708"
      font-size: 30
    }
  }
  dc: {
    label.near: bottom-left
    near: center-left
    style: {
      opacity: 0.4
      fill: "#DDE8FA"
      stroke: "#DDE8FA"
      font-size: 30
    }
  }
  dc_c: {
    style: {
      opacity: 0.9
      fill: "#DDE8FA"
      stroke: "#184da4"
      font-size: 30
    }
  }
  dc_cc: {
    style: {
      opacity: 0.9
      fill: "#9fbef1"
      stroke: "#14418b"
      font-size: 30
    }
  }
  campus: {
    near: bottom-left
    label.near: bottom-left
    style: {
      opacity: 0.4
      fill: "#D9E7D6"
      stroke: "#D9E7D6"
      font-size: 30
    }
  }
  campus_c: {
    style: {
      opacity: 0.9
      fill: "#b2ceac"
      stroke: "#4a7042"
      font-size: 30
    }
  }
  campus_cc: {
    style: {
      opacity: 0.9
      fill: "#91b988"
      stroke: "#3f5f38"
      font-size: 30
    }
  }
}
