classes: {
  red-dash: {
    style: {
      # opacity: 0.4
      # fill: "#FDF2D0"
      # stroke: "#FDF2D0"
      animated: true
      stroke-dash: 5
      stroke: red
      font-size: 30
    }
  }
  green-dash: {
    style: {
      # opacity: 0.4
      # fill: "#FDF2D0"
      # stroke: "#FDF2D0"
      animated: true
      stroke-dash: 5
      stroke: green
      font-size: 30
      font-color: darkgreen
    }
  }
  blue-dash: {
    style: {
      # opacity: 0.4
      # fill: "#FDF2D0"
      # stroke: "#FDF2D0"
      # animated: true
      stroke-dash: 5
      stroke: blue
      font-size: 22
      font-color: blue
      font-size: 30
    }
  }
  blue-bold: {
    style: {
      # opacity: 0.4
      # fill: "#FDF2D0"
      # stroke: "#FDF2D0"
      # animated: true
      # stroke-dash: 5
      stroke: blue
      stroke-width: 6
      font-size: 38
      font-color: blue
    }
  }
}
