grid-gap: 0
grid-columns: 1
app data
body: "" {
  grid-gap: 0
  grid-columns: 2
  static: {
    files-400gb
    logs-50gb
    grid-gap: 0
    grid-columns: 2
  }
  database: {
    grid-gap: 0
    grid-columns: 2
    SQL-80gb
    point-in-time-recovery
  }
}
RTO 2: {
  grid-gap: 0
  grid-columns: 3
  isf/oclc
  Highly Aavailable
  Tier 3 Isilon
}
